### PR TITLE
Misc. cleanups

### PR DESCRIPTION
**Pull request by khaledhosny**
Some compiler warning fixes and removal of dead code.

### CODE REVIEW

**Comment by behdad** [comment]
Thanks Khaled.  Before you touch more of the fribidi guts, let us coordinate and merge @dov's Unicode 6.3 work so we don't have a lot of merging to do...  The current status is here:

  https://github.com/behdad/fribidi/tree/unicode63

Some of the tests were failing for me last time I checked...  I'll see if I can finish this soon.

**Comment by khaledhosny** [comment]
OK, let me know if I can help with that.
(These changes are a bit old, I had them locally while reading `fribidi-main.c` trying to understand why to use the API, and untangling all the `#ifdef`s was not easy).

**Comment by khaledhosny** [comment]
I had test failures in unicode63 branch as well, but I just started with a fresh git clone and both `make check` and `make distcheck` are successful, so I guess it was some stale files files from the master build.

Any thing else blocking the merge of this branch?

**Comment by khaledhosny** [comment]
FWIW, there is a dependency problem in the generated `*.i` files, they even survive `make distcheck`, I had to delete them manually when switching branches to get things working.

**Comment by khaledhosny** [comment]
Is there interest in this PR as well?

**Comment by dov** [comment]
After a quick look, I think only the iconv (a6d3dfe) stuff is relevant. 

Regarding warnings, lots of things have changed and I want to clean all of them up in any case.

And regarding the use of the deprecations, I will change both fribidi.c and fribidi-benchmarks.c to use the new API, as the deprecated API is no longer standards compliant. And  this will make 
be5e074 irrelevant.

So I'll cherry pick a6d3dfe branch and will then close this PR.

Thanks Khaled.

**Comment by dov** [comment]
In the end it applied cleanly so I applied all of it.

**Pull request merged**
