### PR TITLE
meson: allow to disable building tests and binaries

### PR DESCRIPTION
**Pull request by jbkempf**
This allows to optionally not build tests, nor binaries.

### CODE REVIEW

**Comment by vtorri** [comment]
i guess that it should also be done for autotools too, right ?

**Comment by tp-m** [comment]
This looks useful, I'd like that too (only care about meson though at this point).

Personally I'd prefer feature type options here so they can be left to 'auto', but different projects do different things here. It's useful in case tests or tools ever require some external dep, in which case `tests=auto` would just skip it if the dep is not available and `tests=enabled` would make the build error out, which is a useful distinction to be able to make.

**Comment by jbkempf** [comment]
@vtorri the future is meson and so it should be meson only, I believe.

@tp-m I'll do the way that people who maintain this repo prefer. I don't really care about the default, tbh.

**Comment by dov** [comment]
Looks good to me, and I don't mind adding functionality to the meson build only. As far as I'm concerned, I won't shred any tears if autobuild. is deprecated. That said, I'm willing to accept pull requests if someone is bothered enough by lack of the corresponding functionality in autobuild.

**Pull request merged**
