### PR TITLE
WIP: Add fribidi_reorder_runs()

### LINKED ISSUE #30: linear reorder?
Should port to using something like https://github.com/fribidi/linear-reorder/blob/master/linear-reorder.c

@khaledhosny did you say you have that?

### PR DESCRIPTION
**Pull request by khaledhosny**
Uses Behdad’s linear reorder from:
https://github.com/behdad/linear-reorder/

Rebased on master, and partially reverts d36fab04a6332952556bbf1023c6ba54015ec4c4, but I didn’t actually test it, just to see if this is the kind of API we want. Supersedes #11, and should fix #30.

### CODE REVIEW

**Comment by behdad** [comment]
So this one outputs the runs in visual order.  From a memory handling point of view, the size of the output arrays is not specified.  How's that supposed to work?

**Comment by behdad** [comment]
Also, please prototype Pango using new API to check it works.

**Comment by khaledhosny** [comment]
> From a memory handling point of view, the size of the output arrays is not specified. How's that supposed to work?

The current assumption is that they are equal to the number of runs, but that is broken indeed. So should I have one parameter for the length of all output arrays (they must all be of the same length then), or one for each array?

**Comment by behdad** [comment]
Works for me.  If you can use it raqm successfully, please merge.  Bonus if also in pango.

**Pull request closed without merging**
