### PR TITLE
Update Unicode character databases to v16.0.0

### PR DESCRIPTION
**Pull request by khaledhosny**

### CODE REVIEW

**Comment by dov** [comment]
I prepared for the release, but the ci tests fails under Ubuntu-latest for `make distcheck`. However I have tested under both Fedora 40, and under Ubuntu 24.04, and `make distcheck` passes under both without errors. I'll setup a Ubuntu-latest box in the next few days to look into this, but if @khaledhosny or @behdad has any idea, I'd be happy to hear.

**Comment by behdad** [comment]
When I run the tests locally (on Fedora 39), I see `test_CapRTL_explicit` fail with some weird output. Not sure if it's related.

**Comment by behdad** [comment]
> When I run the tests locally (on Fedora 39), I see `test_CapRTL_explicit` fail with some weird output. Not sure if it's related.

Not sure what was wrong, but seemed transient. Don't know what's wrong with the CI.

**Comment by dov** [comment]
After adding uploading of the log as an artifact on failure, the CI action suddenly passed. Go figure. In any case, I made a new release.

**Pull request merged**
