### PR TITLE
Drop glib dependency

### PR DESCRIPTION
**Pull request by khaledhosny**
This PR drops the optional glib dependency and provides the few missing features that depended on glib.

No need to merge this immediately, I had it locally for a while and thought to send it before I forget about it.

### CODE REVIEW

**Comment by bkuhls** [comment]
This line needs to removed as well:
https://github.com/behdad/fribidi/blob/master/fribidi.pc.in#L10

Otherwise other packages searching for fribidi will fail, for example libass:
```
configure: error: Package requirements (fribidi >= 0.19.0) were not met:

Package @MISC_PACKAGES@ was not found in the pkg-config search path.
Perhaps you should add the directory containing `@MISC_PACKAGES@.pc'
to the PKG_CONFIG_PATH environment variable
Package '@MISC_PACKAGES@', required by 'fribidi', not found
```

**Comment by khaledhosny** [comment]
> This line needs to removed as well:
https://github.com/behdad/fribidi/blob/master/fribidi.pc.in#L10

Thanks, removed.

**Comment by khaledhosny** [comment]
Is there any interest in this PR? I can try to update it, otherwise it should be closed.

**Comment by behdad** [comment]
I like these.  We can also include stdint.h; pretty much anything we use in HarfBuzz is ok to use here directly.

**Comment by dov** [comment]
I certainly don't mind, but I would appreciate if you can make the pull request merge cleanly on the current master.

**Comment by khaledhosny** [comment]
Cleaned up and rebased.

**Comment by dov** [comment]
Thanks! Merged.

**Pull request merged**
