### PR TITLE
meson: Declare libfribidi as a dependency for usage as a subproject

### PR DESCRIPTION
**Pull request by nirbheek**
Needed for:

https://gitlab.gnome.org/GNOME/pango/merge_requests/22

https://gitlab.gnome.org/GNOME/gtk/merge_requests/232

### CODE REVIEW

**Comment by khaledhosny** [comment]
`ninja test` seems to be failing, not sure if this is related to this PR.

**Comment by nirbheek** [comment]
Ah, that's a meson bug that's been fixed but isn't in a stable release yet. It only shows up on Windows. I'll push a fix for it.

**Comment by nirbheek** [comment]
That fixes it.

**Comment by nirbheek** [comment]
FWIW, that bug is not related to this PR and would've happened with any PR, so the workaround should go in anyway :)

**Comment by khaledhosny** [comment]
Thanks!

**Pull request merged**
